### ISSUE TITLE
More sorting options!

### ISSUE THREAD

**Issue by SleepingPanda** [AnimeNeko/Atarashii#188]
Would it be possible to add more sorting options such as: Sort by last updated/watched and the inverse & Sort by title and the inverse?

In some lists, such as the 'Completed' list and the 'In Progress' list, it's time consuming to scroll down to the bottom if it's very long. Including more sorting options would be very helpful in this type of scenario.

**Comment by ratan12** [comment]
We need to think of a good solution for this. We now support AL and I want to use the browse page (http://anilist-api.readthedocs.org/en/latest/anime.html#browse).

**Comment by ratan12** [comment]
I added some new sorting options like score, status, type, priority and progress. 917ea1b
