### ISSUE TITLE
Intent Based Updates (+3rd party hooks)

### ISSUE THREAD

**Issue by AnimaSA** [AnimeNeko/Atarashii#29]
At some unspecified time in the future, I'd like for Atarashii! to move to intent based updates. What that means is that we only need our AsyncTasks in one place, thus cleaner code, and that third party apps that request the permissions can leverage Atarashii! as an easy way to work with MAL.

What this entails, as far as I know is:
      -BroadcastReceiver to receive and hand off intents to a..
      -Service that will process the request specified by the intent
      -And some sort of communications back to the app that fired the intent, possibly a broadcast message for the app to receive

So with this, third party apps, for example a manga reader, would be able to fire an intent saying "I've read a chapter", and have Atarashii! handle it, updating both itself and MAL. Also our internal code will be cleaner and more abstracted, which is always good.

**Comment by Efreak** [comment]
An advantage of sending the mal item id to the app is that it would keep atarashii up to date. A second advantage would be not having to give my password to multiple apps. I trust Tachiyomi, but I don't necessarily trust other apps that might add this ability.

**Comment by ratan12** [comment]
We actually have noticed that there are some apps out there which are collecting passwords and usernames.

This enchantment will require some investigation about security issues and the best way to handle it for Devs
