### ISSUE TITLE
Display the rating

### ISSUE THREAD

**Issue by Kcchouette** [AnimeNeko/Atarashii#317]
The new star system for the 2.0 beta 2 doesn't show the rating label (masterpiece - 10 ;
Awesome …)

Can you show it somewhere to see easily with rating I write? (And too when I want to change, I don't know if 4 stars = 8 or 7, etc)

**Comment by ratan12** [comment]
The star rating system will get replaced by a simple numberpicker to make it easy to support MAL & AL #372
