### ISSUE TITLE
It looks like your API is broken

### ISSUE THREAD

**Issue by Hocchibi** [AnimeNeko/Atarashii#322]
Hi.Recently your API started to behave strange.
http://www.youtube.com/watch?v=RamfcJAIKho (latest stable Atarashii from google play, Android 5.0.2 stock)

**Comment by dgw** [comment]
Known issue.
https://plus.google.com/u/0/106001822498547702835/posts/7bJ497QZxvQ

**Comment by ratan12** [comment]
Our API service, which is used by the application for communicating with MyAnimeList, has been blocked by the owner of the MyAnimeList website. The Atarashii! application will not work until we are unblocked.﻿

Read the URL that dgw posted.

**Comment by motokochan** [comment]
I'll leave this open for now so others can see it, but it's not really a bug.

**Comment by ratan12** [comment]
We are unblocked again to I am closing this ^^
