### ISSUE TITLE
Rating Display Issues

### ISSUE THREAD

**Issue by motokochan** [AnimeNeko/Atarashii#372]
From a store review, it seems that some ratings are displaying incorrectly. For example, a personal rating will be set at 7 (3.5 stars) but will display at 8 (4 stars).

I have not tried to reproduce the issue yet.

**Comment by ratan12** [comment]
Don't bother I think it is time to retire the Stars rating. with the new 1.0 - 10 scale it would be a mess. let alone 1 - 100
