### ISSUE TITLE
"Prequel" is missing

### ISSUE THREAD

**Issue by Kcchouette** [AnimeNeko/Atarashii#374]
Example from [High School DxD Born](http://myanimelist.net/anime/24703/High_School_DxD_BorN). Its prequel is [High School DxD New: Oppai, Tsutsumimasu!](http://myanimelist.net/anime/30300/High_School_DxD_New:_Oppai_Tsutsumimasu!)

![screenshot_2015-04-07-19-42-48](https://cloud.githubusercontent.com/assets/3000936/7029538/a44d3c96-dd5e-11e4-92a9-8003f0bbe298.png)

This error may occur on a few animes.  At present,  I've only seen this on DxD Born.

**Comment by ratan12** [comment]
Actually this could be an API bug. We need to determine it first.

**Comment by motokochan** [comment]
It's an API bug. Closing here and opening on the API project.

New bug: https://bitbucket.org/ratan12/atarashii-api/issue/51/anime-relationship-parsing-issues

**Comment by Kcchouette** [comment]
Ok, thanks :)
