### ISSUE TITLE
Move Overflow on Cover Away from Edge

### ISSUE THREAD

**Issue by srvrguy** [AnimeNeko/Atarashii#394]
The overflow menu for each cover item is very close to the corner currently. This makes it a bit difficult to target easily on the right edge. In some cases, it can overlap the scrollbar area, causing unintended scrolling.

I recommend we move the menu in a bit to reduce chances of overlapping.

This issue was original reported by a Play Store reviewer with a Galaxy S5.

**Comment by ratan12** [comment]
we cannot move the menu itself.

Anyway I do not have any problems at all with the menu. The scroll bar gets disabled by android as soon we do not scroll anymore...

**Comment by ratan12** [comment]
maybe add a setting to move the add button to the left side?
