### ISSUE TITLE
Viewpager update

### ISSUE THREAD

**Issue by ratan12** [AnimeNeko/Atarashii#403]
I found a new cool library which we should try out!
https://android-arsenal.com/details/1/1731

It would've be great for AniList

**Comment by motokochan** [comment]
Looks interesting. Perhaps for 2.2 or later?

**Comment by ratan12** [comment]
I have decided that this library is not developed enough. There were many small problems.
Forced to use tabs on all the activities, sometimes the ripple effect wasn't working, margin problems and many things. It was enough.

Instead I implemented the tabs from another library and used a toolbar with custom shadow. I left some observable in the app so that we can implement the awesome material slide later.
The result:
![screenshot_2015-07-05-18-09-22](https://cloud.githubusercontent.com/assets/5322473/8512411/1aa77e42-2341-11e5-9269-9ed4d8d0cc9a.png)

**Comment by ratan12** [comment]
#417
