### ISSUE TITLE
Can't logging when user signed up with facebook

### ISSUE THREAD

**Issue by tomerghelber** [AnimeNeko/Atarashii#438]
My friend succeed to connect only after he enter a password by the "lost password".

I think the connection work with a cookie from facebook and doesn't use a password.
Can we fixed the the logging will handle facebook and so?

I believe the same problem exists with twitter and google+ connections too.

**Comment by motokochan** [comment]
There is currently no possible way for us to support social logins. It's more than just a cookie, it's a full OAuth exchange between MAL and the social media site. There is no way for any third party to process or intercept this. The only workaround is to go into your profile on the website and add a password, then use that to sign in.
