### ISSUE TITLE
Friends list

### ISSUE THREAD

**Issue by tomerghelber** [AnimeNeko/Atarashii#439]
A friend complained that he can't see his friends' lists.

I think this is a really good feature, so I ask for him.

**Comment by dgw** [comment]
There's an entry in the navigation drawer on the left for "My friends" in the current version installed on my phone from the Play Store.

**Comment by motokochan** [comment]
I think the submitter wants to see the lists of other people, as in the lists of friends. That's not currently supported.

**Comment by tomerghelber** [comment]
Yes, as motokochan said

**Comment by ratan12** [comment]
Many users asked for this feature and I will add this in a later release.

**Comment by ratan12** [comment]
This is added in version 2.2
