### ISSUE TITLE
Add friends

### ISSUE THREAD

**Issue by tomerghelber** [AnimeNeko/Atarashii#440]
I need that after a long time.
It would help, not very effective in general use.

**Comment by motokochan** [comment]
Could you provide more details?

**Comment by tomerghelber** [comment]
I want to add an account as a friends via Atarashii.
I can do that in the website and i thought i could be great.

**Comment by motokochan** [comment]
Not currently supported in our back-end API. In fact, there isn't a lot of user-based stuff there yet. Until we get around to adding that in the API, it won't be possible to do in the application, for MyAnimeList at least.
