### ISSUE TITLE
Filter 18+

### ISSUE THREAD

**Issue by tomerghelber** [AnimeNeko/Atarashii#442]
When searching for a manga / anime, sometimes a lot of hentai it poping.
How about to have a flag that will filter them out in search?

**Comment by ratan12** [comment]
We have thought about that. The conclusion was that MAL isn't providing enough information to us.

@motokochan Do you have something to add or did you found any other solutions for this?

**Comment by motokochan** [comment]
At this time, there isn't a good solution. There are some ways to get the data, but they'll increase requests by about 20x. That makes it a non-starter at this time.

**Comment by tomerghelber** [comment]
We could start from the genre. It is parsed in Atarasahii. Only filtering 'Hentai' tag

**Comment by ratan12** [comment]
We can do that only in the detailview. So of you search for an anime you will still get to see hentai in the list.

**Comment by tomerghelber** [comment]
I think its only important in search. 

What is we search bad words in synopsis and titles?

**Comment by motokochan** [comment]
We could potentially block titles with the genre "Hentai". We can get that at least from the basic search results. It wouldn't cover all possible issues, but may be an option. I think the popup on the site has been expanded, as I don't recall that listed previously.

@ratan12 Can we add an option to the application to hide results with "Hentai" as a genre on search? I'll update the API to parse the genres in the search results list. Also, how will this work with AniList?

**Comment by ratan12** [comment]
@motokochan Yes I clearly remember that I did not saw genres in the past. 
We could use the exclude function.
Like this http://myanimelist.net/anime.php?q=toriko&type=0&score=0&status=0&p=0&r=0&sm=0&sd=0&sy=0&em=0&ed=0&ey=0&c%5B%5D=a&c%5B%5D=b&c%5B%5D=c&gx=1&genre%5B%5D=12

It will not show any results with hentai.

And a combination of both URLS will be even better.
http://myanimelist.net/anime.php?c[]=a&c[]=b&c[]=c&c[]=d&c[]=e&c[]=f&c[]=g&q=toriko&type=0&score=0&status=0&p=0&r=0&sm=0&sd=0&sy=0&em=0&ed=0&ey=0&c%5B%5D=a&c%5B%5D=b&c%5B%5D=c&gx=1&genre%5B%5D=12

This will output the old details without any hentai.

AniList has a setting to disable hentai everywhere. We can not acces the settings due security reasons so the user must do that on their website.

**Comment by motokochan** [comment]
Perhaps this should be filtered client-side for consistency? That, or use API options if supported and manual filter on results if not. What do you think?

**Comment by ratan12** [comment]
Client-side will cause the app to make multiple requests if there are many hentais because the screen doesn't get filled which will trigger the scroller. 

Api side is recommended
