### ISSUE TITLE
Overlap of Title and Close link in Forum Comment Dialog

### ISSUE THREAD

**Issue by motokochan** [AnimeNeko/Atarashii#445]
The "Add Comment" title on the overlay dialog for adding a comment on a forum topic is overlapping the "X" to close the overlay, making it impossible to tap. See screenshots.

Perhaps we should use native Cancel/OK controls for this rather than a custom item in the dialog?

![screenshot_2015-09-28-15-33-12](https://cloud.githubusercontent.com/assets/1612403/10184514/2cc6160c-66f2-11e5-9331-75d6b604f911.png)

![screenshot_2015-09-28-15-32-56](https://cloud.githubusercontent.com/assets/1612403/10184513/2cc51acc-66f2-11e5-9f78-f666554265cd.png)

**Comment by ratan12** [comment]
rewrite is planned. It is currently impossible to support decent anilist forum functions.

I have already asked permission for the design and Josh granted it.

**Comment by ratan12** [comment]
Related to: https://atarashii.freshdesk.com/helpdesk/tickets/16

**Comment by ratan12** [comment]
Closing because of the new design rewrite. Atarashii 2.2.1.
