### ISSUE TITLE
Advance search

### ISSUE THREAD

**Issue by tomerghelber** [AnimeNeko/Atarashii#447]
I thought it could really help to find new things if I could you it.
Added a print screen of MAL:
![MAL Advance Search Window](https://cloud.githubusercontent.com/assets/8795860/10559336/395bab4e-74f7-11e5-98d8-6fc0c073f5db.png)

I thing it required to pass arguments to the search url so we need to understands the parameters.

**Comment by ratan12** [comment]
There are still many things to improve in Atarashii and this is also on the list ^^ Anyway thanks for the suggestion!

**Comment by ratan12** [comment]
Added (67d4c30)
