### ISSUE TITLE
Retrofit, apache & support library

### ISSUE THREAD

**Issue by ratan12** [AnimeNeko/Atarashii#456]
The support design library has been updated. The current library is using a new rev number which means that the compile sdk version also needs to be updated.

if the compile version gets an update the old apache library won't be able to get compiled anymore. Retrofit was using it for making requests.if we update retrofit we must use another library which supports this. 

when we upgrade to the newest version I do not how to get the response codes.

I am taking about retrofit 2

**Comment by motokochan** [comment]
Retrofit 2 is still in beta. Do we want to move to a beta library? However, I'm seeing version 1.9.0 in the Gradle file, which doesn't look like an actual stable release.

I'm fine with getting OkHttp in place of the Apache Commons HTTP library, it's a good move anyway.

**Comment by ratan12** [comment]
Retrofit doesn't really matter for now but apache does because I want to update the support design library.

Once retrofit 2 will be released I want to make sure everything works fine. No surprises that we need to adjust more things or add more libraries.
