### ISSUE TITLE
Crash on Settings Scroll when language is "Portuguese Portugal"

### ISSUE THREAD

**Issue by FreezinG117** [AnimeNeko/Atarashii#484]
Hi!

I've found that the app crashes while scrolling in the settings app after the Auto Sync option (Auto Sincronização, in portuguese).

It happens both in the Beta and regular android app.

I'm using Android 5.0.2 / MIUI 7.

Here's the error report:
> java.lang.ArrayIndexOutOfBoundsException: length=7; index=11
> at android.preference.ListPreference.getEntry(ListPreference.java:219)
> at android.preference.ListPreference.getSummary(ListPreference.java:164)
> at android.preference.Preference.onBindView(Preference.java:565)
> at android.preference.Preference.getView(Preference.java:504)
> at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:256)
> at android.widget.AbsListView.obtainView(AbsListView.java:2464)
> at android.widget.ListView.makeAndAddView(ListView.java:1894)
> at android.widget.ListView.fillDown(ListView.java:710)
> at android.widget.ListView.fillGap(ListView.java:674)
> at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5509)
> at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:5004)
> at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
> at android.view.Choreographer.doCallbacks(Choreographer.java:603)
> at android.view.Choreographer.doFrame(Choreographer.java:571)
> at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
> at android.os.Handler.handleCallback(Handler.java:815)
> at android.os.Handler.dispatchMessage(Handler.java:104)
> at android.os.Looper.loop(Looper.java:194)
> at android.app.ActivityThread.main(ActivityThread.java:5549)
> at java.lang.reflect.Method.invoke(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:372)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by ratan12** [comment]
I have seen this before but I do not know what there is wrong because it is working fine here with portuguese :(

**Comment by ratan12** [comment]
I have found the issue. I will publish it in 2.2.6
