### ISSUE TITLE
Cover image don't load when large version isn't available

### ISSUE THREAD

**Issue by qgustavor** [AnimeNeko/Atarashii#486]
[GenericRecord.java](https://github.com/AnimeNeko/Atarashii/blob/05aa063a36259df4d2622e7c3f6c1377069fe60f/Atarashii/src/net/somethingdreadful/MAL/api/MALModels/AnimeManga/GenericRecord.java#L193) always rewrites cover image URL to user large versions. Sometimes (≈ 2% of my list) a large version isn't available, like with [Azumanga Daioh](http://myanimelist.net/anime/66/Azumanga_Daioh/pics), [Bokurano](http://myanimelist.net/anime/1690/Bokurano/pics), [Hidamari Sketch](http://myanimelist.net/anime/1852/Hidamari_Sketch/pics) and [Sailor Moon](http://myanimelist.net/anime/530/Bishoujo_Senshi_Sailor_Moon/pics). When it happens cover_error.png is shown, instead of fallbacking to the normal, non-large, version.

**Comment by ratan12** [comment]
I will try to fix it

**Comment by ratan12** [comment]
Fixed by eb7ad5b
