### ISSUE TITLE
Settings: Auto-synchronisation misunderstanding

### ISSUE THREAD

**Issue by Senbakiri** [AnimeNeko/Atarashii#487]
BRIEF:
There are two "Auto-synchronisation" options in Settings. The difference between them is unclear(I guess the second option means something like "Sync before backup", but I'm not sure).

STEPS_TO_REPRODUCE:
1. Open app.
2. Login (MAL).
3. Open settings.
4. Look at "Sync" and "Backup" sections.
![screenshot_2016-08-18-18-24-28_net somethingdreadful mal](https://cloud.githubusercontent.com/assets/15061472/17781402/dc4a256c-6577-11e6-898b-ed0dabdbe523.jpg)

**Comment by ratan12** [comment]
No it should be an automatically backup scheduler. I wil improve that actually soon.

**Comment by ratan12** [comment]
never mind almost no one was using it so I will remove the backup feature though.
