### ISSUE TITLE
[MAL] Display Anime/Manga tabs only if user has both lists.

### ISSUE THREAD

**Issue by Senbakiri** [AnimeNeko/Atarashii#488]
BRIEF:
I guess there are people who track only one type of content(for example, I do not use mangalist on MAL at all). Now on the main page I always see tabs for switching between anime and manga lists. As far as I do not have manga list, these tabs are useless and the only thing they do is consume space.

STEPS_TO_REPRODUCE:
1. Open app.
2. Login using MAL account which has only one list.

ACTUAL_RESULT:
There is a useless switcher between two lists.

EXPECTED_RESULT:
Screen space is not used for displaying stuff which is definitely useless.

![screenshot_2016-08-21-00-22-46_net somethingdreadful mal](https://cloud.githubusercontent.com/assets/15061472/17834269/ecae0d22-6740-11e6-8afe-85cb1e009a56.jpg)

**Comment by Senbakiri** [comment]
As a solution I can suggest:
1. Manage these tabs visibility using options. It shouldn't be hard to add two checkboxes like "Enable animelist" and "Enable mangalist".
2. Manage these tabs visibility automatically. You can get [user's list](http://myanimelist.net/mangalist/Ratan12) and [history](http://myanimelist.net/history/Ratan12/manga) from Atarashii API which is enough to identify the usefulness of anime or manga list for the user.

**Comment by dgw** [comment]
Automatically detecting which list(s) to enable is problematic because a user might have no entries in one list or the other when first signing into the app, but what happens if they want to add a media type that is hidden? Forcing the user to use the website or another client to add the first item is obviously a non-option. But it's more user friendly than settings.

This should be carefully considered. I'll try to think of more pitfalls and things to keep in mind over the weekend, too.

**Comment by ratan12** [comment]
Why don't we just add it in the settings an option to hide the tabbar?

**Comment by srvrguy** [comment]
I think we should display both lists by default, but we could have an option that allows the user to select which list configuration they want: both, anime only, manga only. If they choose to only show one list, the bar could then disappear.

**Comment by ratan12** [comment]
Yeah, That is a good idea.
That will do it.

Until it will be added I leave this open

**Comment by ratan12** [comment]
Okay I will add a setting in he preferences. I need to change the way the pageAdapter works but it won't be that hard.

**Comment by ratan12** [comment]
![naamloos](https://cloud.githubusercontent.com/assets/5322473/20110808/18f4d9d6-a5e6-11e6-8e1a-2aa6a6abc2ad.png)
