### ISSUE TITLE
Opening and ending songs

### ISSUE THREAD

**Issue by ratan12** [AnimeNeko/Atarashii#490]
It would be nice to add this in the app.
Once you press on it you will go to google or YouTube where you can listen it :)

**Comment by srvrguy** [comment]
The problem comes in the fact that finding legal versions is difficult and those versions are often region locked. Would we just be sending a search for the name or something?

**Comment by ratan12** [comment]
It wil just get the name and convert it into a youtube or Google search url.
So the user will choose on youtube or Google which info/video they want to see.
