### ISSUE TITLE
Tags not supported

### ISSUE THREAD

**Issue by Nomeji** [AnimeNeko/Atarashii#492]
Tags appear in interface but aren't supported.
How to reproduce:
Select anime with tags, go to personal, tags is empty.
or
Select anime, go to personal, add tags, return, reselect same anime, tags is empty.

**Comment by ratan12** [comment]
Which website are you using?
I will look into this issue.

**Comment by Nomeji** [comment]
I experiment this issue on MAL.

**Comment by ratan12** [comment]
I can reproduce it but the funny thing is that I do not see any update command in the log.
It looks like the app does not call the write task.

**Comment by ratan12** [comment]
It looks like after the dirty rewrite the Personal tags was never added as dirty field.
We use a dirty field to determine if we should update a record if the user will press back.

It was never added thus never updated and saved.

Commit 034d57a fixed it.

Thanks for reporting!

**Comment by Nomeji** [comment]
Thanks a lot for fixing this!
I'm not sure that updating the tag when 
modifying is the only problem tho. As I said, tags aren't showing even if they aren't added through the official website.
I detail it better:
How to reproduce:
Add personal tags to an anime with MyAnimeList website. Go to Atarashii on your phone. Select the same anime, go to personal, tags is empty.

**Comment by ratan12** [comment]
Did I just seriously fixed an unknown bug by misunderstanding.
I just tried what you said using the official website and the app is not syncing it.

**Update:**
Apparently there was a code missing in the API models.
Why? I have honestly no idea but it has been fixed now so you can update and read the personal tags in the next minor version.
Commit f8f6fb3

**Comment by Nomeji** [comment]
Ah ah I found two separate bugs in row without even noticing!
Great job, thanks!
