### ISSUE TITLE
Automatic profile update instead of timer?

### ISSUE THREAD

**Issue by Efreak** [AnimeNeko/Atarashii#493]
Would it be possible to automatically check and see if an update is needed by checking the content for `My Profile` > `History` on load and comparing the most recent update to the last sync time? I'm curious also as to whether or not this could be used to reduce sync time.

Also, there's a typo in the [privacy policy](http://www.atarashiiapp.com/privacy-policy), *The API endpoint from which __your__ are calling*.

**Comment by ratan12** [comment]
No it won't. It will mean downloading the history and comparing each item against each item so as example:
200 anime records.
14 history records.
14*200= 2800x we need to compare it (very roughly calculated).

Sync is basically checking the changes and update only them.
Once that is completed it will get the entire animelist.

**Comment by Efreak** [comment]
Shouldn't it be possible to do this by checking the RSS feeds and parsing the title/date of the most recent local sync against the top date in [the](https://myanimelist.net/rss.php?type=rw&u=efreak) [feeds](https://myanimelist.net/rss.php?type=rm&u=efreak)?

**Comment by srvrguy** [comment]
Some things to note:

Keep in mind that we have to handle bi-directional sync. Basically, changes could be made both through the website and the application and we have to apply changes in both directions.

We could check one side by doing the time comparison, but the actual time to handle all the updates with MAL is not going to have a significant reduction as we have to check each title on both lists and compare data to update it. History doesn't show edits to comments, tags, etc.
