### ISSUE TITLE
Archive project?

### ISSUE THREAD

**Issue by IzzySoft** [AnimeNeko/Atarashii#497]
With [the app discontinued](http://atarashiiapp.com/app-discontinued/), may I suggest to archive the project (can be done in the project's settings) to make the fact clear to those ending up here?

**Comment by ratan12** [comment]
I actually planned to revive the project, but I am not sure when. It depends on multiple things.

@srvrguy Is there an (important) update from MAL?

**Comment by srvrguy** [comment]
MAL has been silent about any development with API restoration or anything for third-party devs on their side for months. The last major news was January 15 where MAL announced they were changing ownership once again.

I'll likely be activating archive shortly, as it can always be undone if this existing codebase is going to be used again in the future.

**Comment by IzzySoft** [comment]
Thanks for the details, @srvrguy! Sad to read, though. Could you please drop a last note here before you archive (so I get a "ping")? Thanks!
