### ISSUE TITLE
"Rewatching" items not handled properly

### ISSUE THREAD

**Issue by dgw** [AnimeNeko/Atarashii#80]
MAL is silly about how it handles "rewatching" a series—it took me way longer than it should have to discover that a series only has that checkbox if it's marked "Completed" and not "Currently Watching"—but it's probably worth supporting them properly. I'm going through a few old series with friends, and I marked them as "Rewatching". It's all well and good if I'm marking stuff on my computer, but from my phone/tablet I can't update progress through these shows.

Best case would be to support them identically to the MAL site: Show "Rewatching" items under the "Watching" category, and allow incrementing the episode progress just like a "standard" in-progress show.

And of course, if I'm doing something wrong, and these are staring me right in the face, that's entirely possible. Feel free to tell me I'm a バカ. ;-)

**Comment by ratan12** [comment]
Fixed in #351
Prepared in #350
Added in #345

So I will close this...

**Comment by dgw** [comment]
I know it's been forever and a day since there was activity on this, but the current stable Play Store version doesn't display rewatching shows as such in the "Rewatching" list, nor does it even support displaying or editing the rewatching checkbox value on the Personal tab. Was there a regression in this functionality?

2.1.2 (also noted that the actual version number is not included in the otherwise verbose About activity)

**Comment by ratan12** [comment]
I am working on a database rewrite. I saw some big bugs inside it which will be fixed. I think it is related to one of those.
